{% set name = "pydantic-extra-types" %}
{% set version = "2.7.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pydantic_extra_types-{{ version }}.tar.gz
  sha256: b9d9ddd755fa5960ec5a77cffcbd5d8796a0116e1dfc8f7c3a27fa0041693382

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - pydantic >=2.5.2

test:
  imports:
    - pydantic_extra_types
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pydantic/pydantic-extra-types
  license: MIT
  license_file: LICENSE
  summary: A place for pydantic types that probably shouldn't exist in the main pydantic lib.
  doc_url: https://docs.pydantic.dev/
  dev_url: https://github.com/pydantic/pydantic-extra-types

extra:
  recipe-maintainers:
    - ytausch
