{% set name = "pydantic-extra-types" %}
{% set version = "2.6.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pydantic_extra_types-{{ version }}.tar.gz
  sha256: e9a93cfb245158462acb76621785219f80ad112303a0a7784d2ada65e6ed6cba

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - pydantic >=2.5.2

test:
  imports:
    - pydantic_extra_types
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pydantic/pydantic-extra-types
  license: MIT
  license_file: LICENSE
  summary: A place for pydantic types that probably shouldn't exist in the main pydantic lib.
  doc_url: https://docs.pydantic.dev/
  dev_url: https://github.com/pydantic/pydantic-extra-types

extra:
  recipe-maintainers:
    - ytausch
