{% set name = "pydantic-extra-types" %}
{% set version = "2.10.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: bf8236a63d061eb3ecb1b2afa78ba0f97e3f67aa11dbbff56ec90491e8772edc

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<38]

requirements:
  host:
    - python
    - hatchling
    - pip
  run:
    - python
    - pydantic >=2.5.2
    - typing_extensions
  run_constrained:
    - pendulum >=3.0.0,<4.0.0
    - phonenumbers >=8,<10
    - pycountry >=23
    - python-ulid >=1,<2  # [py<39]
    - python-ulid >=1,<4  # [py>=39]
    - semver >=3.0.2
    - pymongo >=4.0.0,<5.0.0
    - pytz >=2024.1
    - tzdata >=2024.1

# ModuleNotFoundError: No module named 'pycountry'
{% set ignore_tests = " --ignore=tests/test_country_code.py" %}
{% set ignore_tests = ignore_tests + " --ignore=tests/test_currency_code.py" %}
{% set ignore_tests = ignore_tests + " --ignore=tests/test_json_schema.py" %}
{% set ignore_tests = ignore_tests + " --ignore=tests/test_language_codes.py" %}
{% set ignore_tests = ignore_tests + " --ignore=tests/test_scripts.py" %}
# ModuleNotFoundError: No module named 'ulid'
{% set ignore_tests = ignore_tests + " --ignore=tests/test_ulid.py" %}

test:
  source_files:
    - tests
  imports:
    - pydantic_extra_types
  commands:
    - pip check
    - pytest -v {{ ignore_tests }} tests
  requires:
    - pytest
    - pip
    - pytz >=2024.1
    - semver >=3.0.2
    - phonenumbers >=8,<10
    - pendulum >=3.0.0,<4.0.0
    - pymongo >=4.0.0,<5.0.0

about:
  home: https://github.com/pydantic/pydantic-extra-types
  summary: Extra Pydantic types.
  dev_url: https://github.com/pydantic/pydantic-extra-types
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: A place for pydantic types that probably shouldn't exist in the main pydantic lib.
  doc_url: https://docs.pydantic.dev

extra:
  recipe-maintainers:
    - PatrykKups