{% set name = "pydantic-extra-types" %}
{% set version = "2.8.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pydantic_extra_types-{{ version }}.tar.gz
  sha256: 4d2b3c52c1e2e4dfa31bf1d5a37b841b09e3c5a08ec2bffca0e07fc2ad7d5c4a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - pydantic >=2.5.2
  run_constrained:
    - phonenumbers >=8,<9
    - pycountry >=23
    - python-ulid >=1,<2  # [py<39]
    - python-ulid >=1,<3  # [py>=39]
    - pendulum >=3.0.0,<4.0.0

test:
  imports:
    - pydantic_extra_types
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pydantic/pydantic-extra-types
  license: MIT
  license_file: LICENSE
  summary: A place for pydantic types that probably shouldn't exist in the main pydantic lib.
  doc_url: https://docs.pydantic.dev/
  dev_url: https://github.com/pydantic/pydantic-extra-types

extra:
  recipe-maintainers:
    - ytausch
