{% set name = "pydantic-extra-types" %}
{% set version = "2.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: 4e9991959d045b75feb775683437a97991d02c138e00b59176571db9ce634f0e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  host:
    - python
    - pip
    - hatchling
  run:
    - python
    - pydantic >=2.5.2
    - typing_extensions
  run_constrained:
    - pendulum >=3.0.0,<4.0.0
    - phonenumbers >=8,<10
    - pycountry >=23
    - python-ulid >=1,<2  # [py<39]
    - python-ulid >=1,<4  # [py>=39]
    - semver >=3.0.2,<3.1.0
    - pymongo >=4.0.0,<5.0.0
    - pytz >=2024.1
    - python-tzdata >=2024.1
    - tzdata >=2024.1
    - cron-converter >=1.2.2

test:
  source_files:
    - tests
  imports:
    - pydantic_extra_types
  requires:
    - pytest
    - pip
    - pytz
    - semver
    - phonenumbers
    # pendulum 3.1.0 doesn't support py314. Re-enable when pendulum 3.2.0+ is released.
    - pendulum  # [py<314]
    - pymongo
    - pycountry
  commands:
    - pip check
    # 1. missing python-ulid
    # 2. test_json_schema and test_cron are skipped because cron-converter isn't available on the main channel.
    - pytest -v --ignore=tests/test_ulid.py --ignore=tests/test_json_schema.py --ignore=tests/test_cron.py tests  # [py<314]
    # test_pendulum_dt is skipped because it fails on py314 due to pendulum 3.1.0 not supporting py314.
    - pytest -v --ignore=tests/test_ulid.py --ignore=tests/test_json_schema.py --ignore=tests/test_cron.py --ignore=tests/test_pendulum_dt.py tests  # [py==314]

about:
  home: https://github.com/pydantic/pydantic-extra-types
  dev_url: https://github.com/pydantic/pydantic-extra-types
  doc_url: https://docs.pydantic.dev
  summary: Extra Pydantic types.
  description: A place for pydantic types that probably shouldn't exist in the main pydantic lib.
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - PatrykKups